[database]
host = "127.0.0.1"
port = 6500
username = "admin"
password = "password123"
database_name = "gapp_db"
require_ssl = false

[application]
port = 8000
host = "127.0.0.1"
session_secret = "super-long-and-secret-random-key-needed-to-verify-session-cookies"

[google]
client_id = "1008976486908-3mnoloi9956cr0f7bq5t03tru67l17oi.apps.googleusercontent.com"
client_secret = "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"
redirect_url = "http://localhost:8000/sessions/oauth/google"
auth_url = "https://accounts.google.com/o/oauth2/v2/auth"
token_url = "https://www.googleapis.com/oauth2/v3/token"